spring:

  application:
    name: api

  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: root
    password: root

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate.format_sql: true

server:
  error:
    include-stacktrace: never

logging:
  level:
    org:
      springframework:
        security: DEBUG

api:
  security:
    secret: ${JWT_TOKEN}