spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  application:
    name: api

  jpa:
    show-sql: false

    properties:
      hibernate.format_sql: false

