spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vollmed_api
    username: root
    password: root

  application:
    name: api

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate.format_sql: true

# configuración para que este disponible en la red
server:
  address: 0.0.0.0
  port: 8080
  error:
    include-stacktrace: never

logging:
  level:
    org:
      springframework:
        security: DEBUG

api:
  security:
    secret: ${JWT_TOKEN:123456}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

